version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: ./DockerFile
        command: npm run start
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mysql
        env_file:
            - .env

    mysql:
        image: mysql
        env_file: .env
        environment:
            DB_MYSQL_CONNECTION_LIMIT: ${DB_MYSQL_CONNECTION_LIMIT}
            DB_MYSQL_HOST: ${DB_MYSQL_HOST}
            DB_MYSQL_USER: ${DB_MYSQL_USER}
            DB_MYSQL_PORT: ${DB_MYSQL_PORT}
            DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
            DB_MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
        ports:
            - ${DB_MYSQL_PORT}:${DB_MYSQL_PORT}
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config:
